### ISSUE TITLE
documentation for `Web` should be updated

### ISSUE THREAD

**Issue by SkywaveTM** [mastodon-dart/mastodon-oauth2#17]
# 1. What could be improved
[An documentation about web client](https://github.com/mastodon-dart/mastodon-oauth2#1133-web) is just referring [that of `flutter_web_auth_2`](https://pub.dev/packages/flutter_web_auth_2#web). However, the example used in the referring one is not suitable for `mastodon-oauth2` since expected message payload is different. 

```dart
// ❌
window.opener.postMessage({
    'flutter-web-auth-2': window.location.href
  }, window.location.origin);

// ⭕️
window.opener.postMessage(window.location.href, window.location.origin);
```

# 2. Why should this be improved
Developers might fail to use web clients.

# 3. Any risks?
Not much, I believe.

# 4. More information
nope

**Comment by myConsciousness** [comment]
Hi @SkywaveTM , thanks for your feedback :)

It's true that the linked examples in the current README are inappropriate. I would try to improve the documentation, I thank you! :)

**Comment by myConsciousness** [comment]
@all-contributors please add @SkywaveTM for docs , idea
